--[[ Addon Settings Configuration ]]

ENABLE_HERO_RESPAWN = true
UNIVESRAL_SHOP_MODE = false
ALLOW_SAME_HERO_SELECTION = true

HERO_SELECTION_TIME = 30.0
PRE_GAME_TIME = 5.0
POST_GAME_TIME = 60.0
TREE_REGROW_TIME = 60.0

GOLD_PER_TICK = 1
GOLD_TICK_TIME = 1

RECOMMENDED_BUILDS_DISABLED = true
CAMERA_DISTANCE_OVERRIDE = -1

MINIMAP_ICON_SIZE = 1
MINIMAP_CREEP_ICON_SIZE = 1
MINIMAP_RUNE_ICON_SIZE = 1
